#!/usr/bin/env python

# Copyright (C) 2011 CNRS, 2015 the Walkman Consortium
#
# Authors: Antonio El Khoury, Alessio Rocchi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse

from urdf_parser_py.urdf import *
import PyKDL
import math
from ament_index_python.packages import get_package_share_directory
import subprocess
import os


class CapsuleParameters(object):
    """
    CapsuleParameters is an object containing parameters for a capsule
    """

    def __init__(self,
                 length=0.0, radius=0.0,
                 position=PyKDL.Vector(0.0, 0.0, 0.0),
                 orientation=PyKDL.Rotation()):
        self.length = length
        self.p = position
        self.radius = radius
        self.rot = orientation
        self.ep1 = self.p - 0.5*self.length*self.rot.UnitZ()
        self.ep2 = self.p + 0.5*self.length*self.rot.UnitZ()

    @staticmethod
    def from_endpoints(ep1, ep2, radius=0.0, thr=1e-9):
        """
        Generates capsule parameters (center, rotation, radius) starting
        from endpoinds and radius
        :param ep1: first end point
        :param ep2: second endpoint
        :param radius: capsule radius
        """

        axis = ep2 - ep1
        length = axis.Normalize()

        p = .5 * (ep2 + ep1)

        e3 = PyKDL.Vector(0.0,
                          0.0,
                          1.0)
        r = e3 * axis
        s_theta = r.Normalize()
        c_theta = PyKDL.dot(e3, axis)

        theta = math.atan2(s_theta, c_theta)

        rot = PyKDL.Rotation().Rot(r, theta)

        if math.fabs(round(rot[0,2],9)-round(axis[0],9)) > thr:
            print('[warning] numerical inaccuracy detected')

        if math.fabs(round(rot[1,2],9)-round(axis[1],9)) > thr:
            print('[warning] numerical inaccuracy detected')

        if math.fabs(round(rot[2,2],9)-round(axis[2],9)) > thr:
            print('[warning] numerical inaccuracy detected')

        #assert round(rot[0,2],9) == round(axis[0],9) and \
        #       round(rot[1,2],9) == round(axis[1],9) and \
        #       round(rot[2,2],9) == round(axis[2],9)

        return CapsuleParameters(length, radius, p, rot)


class ros2_path_manager(object):
    def __init__(self, mesh_name):
        mesh_filename = mesh_name
        is_package = mesh_filename.find('package://')
        if is_package != -1:
            package_len = mesh_filename.find('/', 10)
            package_name = mesh_filename[10:package_len]
            print(f"package_name: {package_name}")
            ros_path = get_package_share_directory(package_name)
            print(f"ros_path: {ros_path}")
            mesh_filename = ros_path + '/' + mesh_filename[package_len + 1:]

        self.mesh_path = mesh_filename


class CapsuleGenerator(CapsuleParameters):
    def __init__(self, link):
        super(CapsuleGenerator, self).__init__()

        if type(link) is not Link:
            raise Exception('link parameters is not of type Link')

        self._link = None
        self.mesh_path = ''
        self.ros2_path_manager = None

        if link.collision:
            self._link = link
            if type(link.collision.geometry) is Mesh:
                self.ros2_path_manager = ros2_path_manager(link.collision.geometry.filename)

                self.mesh_path = self.ros2_path_manager.mesh_path

                print("Creating capsule data for link %s\n" % self._link.name)
                self._load_or_compute()
            else:
                raise Exception('Specified link\'s collision object is not a mesh')

        else:
            raise Exception('Specified link does not have a collision object')

    def _load_or_compute(self):
        """
        Loads capsule parameters from URDF (through CapsuleWriter) or computes them
        by calling roboptim-capsule
        :return: True on success
        """
        print("Computing capsule from mesh file %s\n" % self.mesh_path)
        self._compute()
        self._save()
        return True

    def _compute(self):
        """
        Computes capsule information by using roboptim-capsule and then converts them to CapsuleParameters
        :return: True on success
        """
        self._params_to_cylinder(self._compute_params())
        return True


    def _save(self):
        """
        Saves the parameters to a file through a CapsuleWriter
        :return: True on success
        """
        collision = Collision(origin=self._link.collision.origin)
        cylinder = Cylinder(self.radius, self.length)

        collision.geometry = cylinder

        mesh_rotation = PyKDL.Rotation().RPY(collision.origin.rotation[0],
                                             collision.origin.rotation[1],
                                             collision.origin.rotation[2], )

        """ we transform the capsule center in parent coordinates """
        offset = mesh_rotation * self.p
        collision.origin.position[0] += offset.x()
        collision.origin.position[1] += offset.y()
        collision.origin.position[2] += offset.z()

        capsule_rotation = mesh_rotation * self.rot
        (R, P, Y) = capsule_rotation.GetRPY()
        collision.origin.rotation[0] = float(R)
        collision.origin.rotation[1] = float(P)
        collision.origin.rotation[2] = float(Y)

        return True

    def _compute_params(self):
        """
        Computes optimal capsule parameters by calling robot_capsule_generator, which in turns uses roboptim-capsule
        :return: a tuple of size 7, where the numbers are strings representing
                 respectively the position of the two endpoint and the radius of the capsule
        """
        if self._link.collision.geometry.scale:
            scale = self._link.collision.geometry.scale
            p = subprocess.Popen(["robot_capsule_generator",
                                  self.mesh_path,
                                  "--scaling",
                                  str(scale[0]),
                                  str(scale[1]),
                                  str(scale[2])], stdout=subprocess.PIPE)
        else:
            p = subprocess.Popen(["robot_capsule_generator", self.mesh_path], stdout=subprocess.PIPE)

        stdout, stderr = p.communicate()

        # try decode if on python3
        try:
            stdout = stdout.decode()
        except:
            pass

        params = stdout.rstrip()

        cylinder_para = params.split('\n')
        cylinder_para = cylinder_para[1:]
        return cylinder_para

    def _params_to_cylinder(self, cylinder_params):
        """
        Transforms capsule parameters as computed by robot_capsule_generator to CapsuleParams
        return True on success
        """
        ep1 = PyKDL.Vector(float(cylinder_params[0]),
                           float(cylinder_params[1]),
                           float(cylinder_params[2]))
        ep2 = PyKDL.Vector(float(cylinder_params[3]),
                           float(cylinder_params[4]),
                           float(cylinder_params[5]))

        self.radius = float(cylinder_params[6])

        capsule_params = CapsuleParameters.from_endpoints(ep1, ep2, self.radius)
        self.length = capsule_params.length
        self.p = capsule_params.p
        self.rot = capsule_params.rot
        return True


if __name__ == '__main__':
    """
    robot_capsule_urdf is a python script that will parse a robot URDF containing
    mesh collision information, and generate an URDF just with collision data where
    links are instead approximated with capsules.
    The capsule is then converted into a cylinder in the URDF, where the position
    of the cylinder will be the mean of the two endpoints plus the original mesh
    offset, and the orientation will be computed by multiplying the original mesh
    rotation matrix with the rotation obtained from the two endpoints ep2 and ep1
    by computing the cross product between e3 and v (in order to align the local
    z axis of the capsule frame to the actual segment connecting the endpoints)

    e3 = [0,0,1]
    v=(ep2-ep1)
    v.Normalize()
    a=e3 x v

    normalizing it in a_norm, computing

    s_theta = a.Norm()
    a.Normalize()
    c_theta= dot(e1,a)

    Finally we will be able to obtain a rotation matrix from an axis angle rotation
    representation where the angle theta and the axis r will be

    theta = atan2(s_theta,c_theta)
    r = a
    """
    parser = argparse.ArgumentParser(usage='robot_capsule_urdf <options> urdf_file capsule_param\nLoad an URDF file')
    parser.add_argument('urdf_file', type=argparse.FileType('r'), nargs='?',
                        default=None, help='URDF file. Use - for stdin')
    parser.add_argument('-o', '--output', help='Output URDF file')
    args = parser.parse_args()
    # Extract robot name and directory

    if args.urdf_file is None:
        print("Error! no urdf_file provided")
        exit()
    else:
        robot = URDF.from_xml_string(args.urdf_file.read())


    links = robot.links

    for link in links:
        if link.collision:
            if type(link.collision.geometry) is Mesh:
                c = CapsuleGenerator(link)

                cylinder = Cylinder(c.radius, c.length)

                link.collision.geometry = cylinder
                link.collision.origin.position[0] = c.p.x()
                link.collision.origin.position[1] = c.p.y()
                link.collision.origin.position[2] = c.p.z()
                (R, P, Y) = c.rot.GetRPY()
                link.collision.origin.rotation[0] = R
                link.collision.origin.rotation[1] = P
                link.collision.origin.rotation[2] = Y

    robot.links = links
    urdf = robot.to_xml_string()
    if args.output:
        open(args.output, 'w').write(urdf)
    else:
        print(urdf)
